### ISSUE TITLE
Fail to deploy on 0.5.0 

### ISSUE THREAD

**Issue by felipefialho** [meandavejustice/gh-pages-deploy#26]
``` 
> gh-pages-deploy

/myuser/node_modules/gh-pages-deploy/index.js:13
var gitcommit = "git commit -a -m '" + (process.argv[3] || cfg.commit || defaultmessage) + "'";
                                                           ^

ReferenceError: cfg is not defined
    at Object.<anonymous> (/myuser/node_modules/gh-pages-deploy/index.js:13:60)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/myuser/node_modules/gh-pages-deploy/bin/gh-pages-deploy:4:14)
    at Module._compile (module.js:652:30)
```

Do you have any idea?

**Comment by LFeh** [comment]
Thanks!

**Comment by ivangretsky** [comment]
Confirm this bug.
